import React, { Children, Component } from 'react';
import { motion } from 'framer-motion';
import {
  PieChart,
  Pie,
  Cell,
  ResponsiveContainer,
  Legend,
  Tooltip } from
'recharts';
import {
  BrainCircuitIcon,
  UserIcon,
  FileCodeIcon,
  AlertTriangleIcon } from
'lucide-react';
const aiVsHumanData = [
{
  name: 'AI Generated',
  value: 89,
  color: '#00F5FF',
  percentage: 36
},
{
  name: 'Human Written',
  value: 158,
  color: '#7B2FFF',
  percentage: 64
}];

const aiFileTypes = [
{
  type: 'Authentication',
  count: 23,
  risk: 'High',
  icon: AlertTriangleIcon
},
{
  type: 'API Routes',
  count: 18,
  risk: 'Medium',
  icon: FileCodeIcon
},
{
  type: 'Components',
  count: 31,
  risk: 'Low',
  icon: FileCodeIcon
},
{
  type: 'Utilities',
  count: 17,
  risk: 'Medium',
  icon: FileCodeIcon
}];

const containerVariants = {
  hidden: {
    opacity: 0
  },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1
    }
  }
};
const itemVariants = {
  hidden: {
    opacity: 0,
    y: 20
  },
  visible: {
    opacity: 1,
    y: 0
  }
};
const CustomTooltip = ({ active, payload }: any) => {
  if (active && payload && payload.length) {
    return (
      <div className="glass-panel px-3 py-2 rounded-lg border-neon-cyan/30">
        <p className="text-sm font-semibold text-white">{payload[0].name}</p>
        <p className="text-xs text-white/60">
          {payload[0].value} files ({payload[0].payload.percentage}%)
        </p>
      </div>);

  }
  return null;
};
export function AIDetectionTab() {
  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="grid grid-cols-12 gap-6">
      
      {/* AI vs Human Breakdown */}
      <motion.div variants={itemVariants} className="col-span-12 lg:col-span-6">
        <div className="glass-panel rounded-2xl p-6 h-full">
          <h3 className="text-lg font-display font-semibold mb-6 flex items-center">
            <BrainCircuitIcon className="h-5 w-5 mr-2 text-neon-cyan" />
            Code Origin Distribution
          </h3>

          <div className="h-80 flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={aiVsHumanData}
                  cx="50%"
                  cy="50%"
                  labelLine={false}
                  label={({ name, percentage }) => `${name}: ${percentage}%`}
                  outerRadius={100}
                  fill="#8884d8"
                  dataKey="value"
                  animationDuration={1000}>
                  
                  {aiVsHumanData.map((entry, index) =>
                  <Cell
                    key={`cell-${index}`}
                    fill={entry.color}
                    stroke="none" />

                  )}
                </Pie>
                <Tooltip content={<CustomTooltip />} />
              </PieChart>
            </ResponsiveContainer>
          </div>

          <div className="grid grid-cols-2 gap-4 mt-6">
            <div className="bg-neon-cyan/10 border border-neon-cyan/30 rounded-xl p-4">
              <div className="flex items-center justify-between mb-2">
                <BrainCircuitIcon className="h-5 w-5 text-neon-cyan" />
                <span className="text-2xl font-display font-bold text-white">
                  89
                </span>
              </div>
              <p className="text-xs text-white/60">AI-Generated Files</p>
              <p className="text-sm font-semibold text-neon-cyan mt-1">
                36% of codebase
              </p>
            </div>

            <div className="bg-neon-purple/10 border border-neon-purple/30 rounded-xl p-4">
              <div className="flex items-center justify-between mb-2">
                <UserIcon className="h-5 w-5 text-neon-purple" />
                <span className="text-2xl font-display font-bold text-white">
                  158
                </span>
              </div>
              <p className="text-xs text-white/60">Human-Written Files</p>
              <p className="text-sm font-semibold text-neon-purple mt-1">
                64% of codebase
              </p>
            </div>
          </div>
        </div>
      </motion.div>

      {/* AI File Categories */}
      <motion.div variants={itemVariants} className="col-span-12 lg:col-span-6">
        <div className="glass-panel rounded-2xl p-6 h-full">
          <h3 className="text-lg font-display font-semibold mb-6">
            AI-Generated by Category
          </h3>

          <div className="space-y-4">
            {aiFileTypes.map((category, idx) => {
              const Icon = category.icon;
              const riskColor =
              category.risk === 'High' ?
              'neon-orange' :
              category.risk === 'Medium' ?
              'yellow-400' :
              'neon-cyan';
              return (
                <motion.div
                  key={category.type}
                  initial={{
                    opacity: 0,
                    x: -20
                  }}
                  animate={{
                    opacity: 1,
                    x: 0
                  }}
                  transition={{
                    delay: idx * 0.1
                  }}
                  className="bg-white/[0.02] border border-white/10 rounded-xl p-4 hover:bg-white/[0.04] transition-all">
                  
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <div className="p-2 bg-white/5 rounded-lg">
                        <Icon className="h-5 w-5 text-white/70" />
                      </div>
                      <div>
                        <h4 className="font-medium text-white">
                          {category.type}
                        </h4>
                        <p className="text-xs text-white/50">
                          {category.count} files detected
                        </p>
                      </div>
                    </div>
                    <span
                      className={`px-3 py-1 text-xs font-semibold rounded-full border bg-${riskColor}/10 text-${riskColor} border-${riskColor}/30`}>
                      
                      {category.risk} Risk
                    </span>
                  </div>

                  {/* Progress Bar */}
                  <div className="mt-3 h-2 bg-white/5 rounded-full overflow-hidden">
                    <motion.div
                      initial={{
                        width: 0
                      }}
                      animate={{
                        width: `${category.count / 89 * 100}%`
                      }}
                      transition={{
                        duration: 1,
                        delay: idx * 0.1 + 0.3
                      }}
                      className={`h-full bg-${riskColor}/50`} />
                    
                  </div>
                </motion.div>);

            })}
          </div>

          {/* Detection Accuracy */}
          <div className="mt-6 pt-6 border-t border-white/10">
            <div className="flex items-center justify-between">
              <span className="text-sm text-white/60">Detection Accuracy</span>
              <div className="flex items-center space-x-2">
                <div className="h-2 w-32 bg-white/10 rounded-full overflow-hidden">
                  <motion.div
                    initial={{
                      width: 0
                    }}
                    animate={{
                      width: '78%'
                    }}
                    transition={{
                      duration: 1,
                      delay: 0.5
                    }}
                    className="h-full bg-neon-cyan" />
                  
                </div>
                <span className="text-sm font-display font-bold text-neon-cyan">
                  78%
                </span>
              </div>
            </div>
          </div>
        </div>
      </motion.div>
    </motion.div>);

}